### ISSUE TITLE
Tweedle kullanarak tweets.json dosyası oluşturulmalı.

### ISSUE THREAD

**Issue by ahmetsina** [ahmetsina/hoverboard#2]
Şuan tweetleri çeken herhangi bir sistem yok. Dokümantasyonda tavsiye edilen tweedle'ı kullanıp herokuya deploy edilerek bir json dosyası oluşturulabilir. Takip edilmesi gereken etiket : **#dftek**

**Comment by umit-ozturk** [comment]
.
